In [24]:
import h3
import pandas as pd
pd.options.mode.chained_assignment = None
from keplergl import KeplerGl

dfh3 = pd.read_csv('../data/df_points_2019_2020.csv')
dfh3['hex_id'] = 0
dfh3

,Unnamed: 0,bike_id,lat,lng,timestood,time_start,time_end,flag,hex_id
0,0,71949.0,51.334071,12.399960,45,2018-12-31 23:14:49,2018-12-31 23:59:59,0.0,0
1,1,71949.0,51.335429,12.324583,122,2019-01-01 01:41:33,2019-01-01 03:44:04,0.0,0
2,2,71949.0,51.343813,12.381495,592,2019-01-01 04:14:54,2019-01-01 14:07:13,0.0,0
3,3,71949.0,51.341518,12.365614,586,2019-01-01 14:13:45,2019-01-01 23:59:59,0.0,0
4,4,71949.0,51.345950,12.356816,144,2019-01-03 21:35:13,2019-01-03 23:59:59,0.0,0
...,...,...,...,...,...,...,...,...,...
1587001,1587001,93544.0,51.321160,12.269497,1439,2020-07-21 00:00:00,2020-07-21 23:59:59,1.0,0
1587002,1587002,93544.0,51.321160,12.269497,1439,2020-07-22 00:00:00,2020-07-22 23:59:59,1.0,0
1587003,1587003,93544.0,51.321160,12.269497,1439,2020-07-23 00:00:00,2020-07-23 23:59:59,1.0,0
1587004,1587004,93544.0,51.321160,12.269497,1439,2020-07-24 00:00:00,2020-07-24 23:59:59,1.0,0
1587005,1587005,93544.0,51.321160,12.269497,1361,2020-07-25 00:00:00,2020-07-25 22:41:47,0.0,0

In [25]:
for ind in dfh3.index:
    dfh3['hex_id'][ind] = h3.geo_to_h3(dfh3['lat'][ind], dfh3['lng'][ind], 8)
dfh3

,Unnamed: 0,bike_id,lat,lng,timestood,time_start,time_end,flag,hex_id
0,0,71949.0,51.334071,12.399960,45,2018-12-31 23:14:49,2018-12-31 23:59:59,0.0,881f1a1659fffff
1,1,71949.0,51.335429,12.324583,122,2019-01-01 01:41:33,2019-01-01 03:44:04,0.0,881f1a8dd3fffff
2,2,71949.0,51.343813,12.381495,592,2019-01-01 04:14:54,2019-01-01 14:07:13,0.0,881f1a8cb1fffff
3,3,71949.0,51.341518,12.365614,586,2019-01-01 14:13:45,2019-01-01 23:59:59,0.0,881f1a8cb5fffff
4,4,71949.0,51.345950,12.356816,144,2019-01-03 21:35:13,2019-01-03 23:59:59,0.0,881f1a8cabfffff
...,...,...,...,...,...,...,...,...,...
1587001,1587001,93544.0,51.321160,12.269497,1439,2020-07-21 00:00:00,2020-07-21 23:59:59,1.0,881f1a8debfffff
1587002,1587002,93544.0,51.321160,12.269497,1439,2020-07-22 00:00:00,2020-07-22 23:59:59,1.0,881f1a8debfffff
1587003,1587003,93544.0,51.321160,12.269497,1439,2020-07-23 00:00:00,2020-07-23 23:59:59,1.0,881f1a8debfffff
1587004,1587004,93544.0,51.321160,12.269497,1439,2020-07-24 00:00:00,2020-07-24 23:59:59,1.0,881f1a8debfffff
1587005,1587005,93544.0,51.321160,12.269497,1361,2020-07-25 00:00:00,2020-07-25 22:41:47,0.0,881f1a8debfffff

---> eventually delete flag

In [26]:
dfh3.to_csv('../data/df_points_2019_2020_h8.csv', index=False)

In [20]:
listhex = {}
for ind in dfh3.index:
    if dfh3['hex_id'][ind] not in listhex:
        listhex[dfh3['hex_id'][ind]] = 0

In [21]:
listhex

{'881f1a1647fffff': 0,
 '881f1a8cb7fffff': 0,
 '881f1a8cb1fffff': 0,
 '881f1a8d91fffff': 0,
 '881f1ab965fffff': 0,
 '881f1a8ca5fffff': 0,
 '881f1ab961fffff': 0,
 '881f1a8cb3fffff': 0,
 '881f1a1659fffff': 0,
 '881f1a8d9bfffff': 0,
 '881f1a1651fffff': 0,
 '881f1a1655fffff': 0,
 '881f1a8d99fffff': 0,
 '881f1a164bfffff': 0,
 '881f1a8cb5fffff': 0,
 '881f1a8c83fffff': 0,
 '881f1a8c81fffff': 0,
 '881f1a8c91fffff': 0,
 '881f1a165bfffff': 0,
 '881f1a1643fffff': 0,
 '881f1a1653fffff': 0,
 '881f1a161bfffff': 0,
 '881f1a8d8bfffff': 0,
 '881f1a8dd7fffff': 0,
 '881f1a8dd3fffff': 0,
 '881f1a8ca3fffff': 0,
 '881f1a165dfffff': 0,
 '881f1a1649fffff': 0,
 '881f1a1641fffff': 0,
 '881f1a8d93fffff': 0,
 '881f1a1657fffff': 0,
 '881f1ab969fffff': 0,
 '881f1a8cbdfffff': 0,
 '881f1a1611fffff': 0,
 '881f1ab96dfffff': 0,
 '881f1a8ca7fffff': 0,
 '881f1ab92dfffff': 0,
 '881f1ab929fffff': 0,
 '881f1ab967fffff': 0,
 '881f1a8c9dfffff': 0,
 '881f1a1601fffff': 0,
 '881f1a164dfffff': 0,
 '881f1a8ddbfffff': 0,
 '881f1a8c8dfffff': 0,
 '881f1a8c89fffff': 0,
 '881f1a8cd5fffff': 0,
 '881f1abb25fffff': 0,
 '881f1a8cabfffff': 0,
 '881f1a8c87fffff': 0,
 '881f1a8c8bfffff': 0,
 '881f1ab963fffff': 0,
 '881f1a1605fffff': 0,
 '881f1a160dfffff': 0,
 '881f1a1609fffff': 0,
 '881f1a161dfffff': 0,
 '881f1a1757fffff': 0,
 '881f1ab925fffff': 0,
 '881f1a1619fffff': 0,
 '881f1a8cb9fffff': 0,
 '881f1a8c33fffff': 0,
 '881f1a8c95fffff': 0,
 '881f1a8d97fffff': 0,
 '881f1a8db7fffff': 0,
 '881f1a8d9dfffff': 0,
 '881f1a8dd9fffff': 0,
 '881f1a8d95fffff': 0,
 '881f1a8dbbfffff': 0,
 '881f1a8c93fffff': 0,
 '881f1ab90dfffff': 0,
 '881f1a8db3fffff': 0,
 '881f1a1759fffff': 0,
 '881f1a8cc5fffff': 0,
 '881f1a8c85fffff': 0,
 '881f1a8ce5fffff': 0,
 '881f1a8cd9fffff': 0,
 '881f1a8c31fffff': 0,
 '881f1a8ca1fffff': 0,
 '881f1a1719fffff': 0,
 '881f1a1739fffff': 0,
 '881f1a1669fffff': 0,
 '881f1a1607fffff': 0,
 '881f1a8cd3fffff': 0,
 '881f1a8cadfffff': 0,
 '881f1a8cc7fffff': 0,
 '881f1ab905fffff': 0,
 '881f1a1715fffff': 0,
 '881f1a8cbbfffff': 0,
 '881f1a8d8dfffff': 0,
 '88754e6499fffff': 0,
 '881f1a8cc3fffff': 0,
 '881f1a16c5fffff': 0,
 '881f1a8c9bfffff': 0,
 '881f1ab945fffff': 0,
 '881f1a160bfffff': 0,
 '881f1abb27fffff': 0,
 '881f1a8d83fffff': 0,
 '881f1a1635fffff': 0,
 '881f1a163dfffff': 0,
 '881f1a1645fffff': 0,
 '881f1a1753fffff': 0,
 '881f1a8dd1fffff': 0,
 '881f1a8cebfffff': 0,
 '881f1a1639fffff': 0,
 '881f1ab901fffff': 0,
 '881f1a1603fffff': 0,
 '881f1a8c13fffff': 0,
 '881f1a8cd1fffff': 0,
 '881f1ab947fffff': 0,
 '881f1ab951fffff': 0,
 '881f1a8dd5fffff': 0,
 '881f1a8cd7fffff': 0,
 '881f1a8c99fffff': 0,
 '881f1a1615fffff': 0,
 '881f1ab96bfffff': 0,
 '881f1a8de3fffff': 0,
 '881f1a8de1fffff': 0,
 '881f1abb21fffff': 0,
 '881f1ab949fffff': 0,
 '881f1a8d87fffff': 0,
 '881f1a1443fffff': 0,
 '881f1a8d81fffff': 0,
 '881f1a8c37fffff': 0,
 '881f1a8cdbfffff': 0,
 '881f1a173dfffff': 0,
 '881f1a170bfffff': 0,
 '881f1a8cc1fffff': 0,
 '881f1a8ca9fffff': 0,
 '881f1a1711fffff': 0,
 '881f1a155bfffff': 0,
 '881f1a12dbfffff': 0,
 '881f1ab931fffff': 0,
 '881f1ab907fffff': 0,
 '881f1abb61fffff': 0,
 '881f1a8ce3fffff': 0,
 '881f1a8cddfffff': 0,
 '881f1a8c17fffff': 0,
 '881f1a8cedfffff': 0,
 '881f1a1621fffff': 0,
 '881f1a171bfffff': 0,
 '881f1a162bfffff': 0,
 '881f1a16e1fffff': 0,
 '881f1a1663fffff': 0,
 '881f1abb65fffff': 0,
 '881f1a8c97fffff': 0,
 '881f1a8ec1fffff': 0,
 '881f1a8ccbfffff': 0,
 '881f1abb2bfffff': 0,
 '881f1abb35fffff': 0,
 '881f1ab921fffff': 0,
 '881f1a1747fffff': 0,
 '881f1a8eddfffff': 0,
 '881f1a8dddfffff': 0,
 '881f1a166bfffff': 0,
 '881f1a8dadfffff': 0,
 '881f1a163bfffff': 0,
 '881f1a8c15fffff': 0,
 '881f1a8ce7fffff': 0,
 '881f1a8c0bfffff': 0,
 '881f1a8d85fffff': 0,
 '881f1ab90bfffff': 0,
 '881f1a8ce9fffff': 0,
 '881f1a15d1fffff': 0,
 '881f1a1707fffff': 0,
 '881f1ab941fffff': 0,
 '881f1a8c61fffff': 0,
 '881f1a8de7fffff': 0,
 '881f1ab915fffff': 0,
 '881f1a16e9fffff': 0,
 '881f1a1617fffff': 0,
 '881f1a1661fffff': 0,
 '881f1a141dfffff': 0,
 '881f1a1637fffff': 0,
 '881f1a1449fffff': 0,
 '881f1a1627fffff': 0,
 '881f1a8535fffff': 0,
 '881f1a8db9fffff': 0,
 '881f1a8de9fffff': 0,
 '881f1a8c39fffff': 0,
 '881f1a8537fffff': 0,
 '881f1ab955fffff': 0,
 '881f1a8d89fffff': 0,
 '881f1a1455fffff': 0,
 '881f1a166dfffff': 0,
 '881f1a1705fffff': 0,
 '881f1a8da9fffff': 0,
 '881f1a1665fffff': 0,
 '881f1a8ea7fffff': 0,
 '881f1a1625fffff': 0,
 '881f1a144dfffff': 0,
 '881f1a8eb7fffff': 0,
 '881f1a1701fffff': 0,
 '881f1a1629fffff': 0,
 '881f1abb37fffff': 0,
 '881f1a1733fffff': 0,
 '881f1a8ce1fffff': 0,
 '881f1ab94dfffff': 0,
 '881f1aab49fffff': 0,
 '881f1a162dfffff': 0,
 '881f1a16e5fffff': 0,
 '881f1abb23fffff': 0,
 '881f1a8debfffff': 0,
 '881f1a16cdfffff': 0,
 '881f1a1689fffff': 0,
 '881f1a8db5fffff': 0,
 '881f1a8de5fffff': 0,
 '881f1abb6bfffff': 0,
 '881f1b54bbfffff': 0,
 '881f1b54b9fffff': 0,
 '881f1b54b1fffff': 0,
 '881f1b4659fffff': 0,
 '881f1b464bfffff': 0,
 '881f1a12d3fffff': 0,
 '881f1a1447fffff': 0,
 '881f1a8c55fffff': 0,
 '881f1a16b5fffff': 0,
 '881f1a16edfffff': 0,
 '881f1a10d1fffff': 0,
 '881f1a8dc7fffff': 0,
 '881f1a1743fffff': 0,
 '881f1a8eb3fffff': 0,
 '881f1a8c1bfffff': 0,
 '881f1a8c27fffff': 0,
 '881f1a16a3fffff': 0,
 '881f1ab903fffff': 0,
 '881f1a15cbfffff': 0,
 '881f1ab829fffff': 0,
 '881f1a8dbdfffff': 0,
 '881f1a8e37fffff': 0,
 '881f1abb2dfffff': 0,
 '881f1a8dc9fffff': 0,
 '881f1a145dfffff': 0,
 '881f1ab927fffff': 0,
 '881f1ab92bfffff': 0,
 '881f1ab939fffff': 0,
 '881f1a8dc3fffff': 0,
 '881f1a8a85fffff': 0,
 '881f1a8c43fffff': 0,
 '881f1abb45fffff': 0,
 '881f1a8c19fffff': 0,
 '881f1a1415fffff': 0,
 '881f1a8ea5fffff': 0,
 '881f1a1751fffff': 0,
 '881f1a16a1fffff': 0,
 '881f1a8d45fffff': 0,
 '881f1a1543fffff': 0,
 '881f1a8c3dfffff': 0,
 '881f1ab923fffff': 0,
 '881f1abb29fffff': 0,
 '881f1a12d7fffff': 0,
 '881f1a1709fffff': 0,
 '881f1a8c11fffff': 0,
 '881f1a1631fffff': 0,
 '881f1a12d9fffff': 0,
 '881f1a1469fffff': 0,
 '881f1ab9b3fffff': 0,
 '881f1a8f03fffff': 0,
 '881f1a8ea3fffff': 0,
 '881f1a140bfffff': 0,
 '881f1ac639fffff': 0,
 '881f1abb57fffff': 0,
 '881f1a151bfffff': 0,
 '881f1a144bfffff': 0,
 '881f1abb01fffff': 0,
 '881f1a175dfffff': 0,
 '881f1ab909fffff': 0,
 '881f1a8ccdfffff': 0,
 '881f1a1717fffff': 0,
 '881f1a8f53fffff': 0,
 '881f1a173bfffff': 0,
 '881f1a1551fffff': 0,
 '881f1a8531fffff': 0,
 '881f1a175bfffff': 0,
 '881f1a1613fffff': 0,
 '881f1ab9bbfffff': 0,
 '881f1a16ebfffff': 0,
 '881f1abb31fffff': 0,
 '881f1a8533fffff': 0,
 '881f1a12c3fffff': 0,
 '881f1a16c7fffff': 0,
 '881f1a1545fffff': 0,
 '881f1a1459fffff': 0,
 '881f1abb1dfffff': 0,
 '881f1a30e5fffff': 0,
 '881f1abb3dfffff': 0,
 '881f1a8e21fffff': 0,
 '881f1a15d9fffff': 0,
 '881f1ab943fffff': 0,
 '881f1ab989fffff': 0,
 '881f1a8dabfffff': 0,
 '881f1ab91dfffff': 0,
 '881f1a145bfffff': 0,
 '881f1a8c53fffff': 0,
 '881f1ab9edfffff': 0,
 '881f1a8eedfffff': 0,
 '881f1ab93bfffff': 0,
 '881f1a1405fffff': 0,
 '881f1a1403fffff': 0,
 '881f1a8da5fffff': 0,
 '881f1a8eb9fffff': 0,
 '881f1ab9c5fffff': 0,
 '881f1a8dcdfffff': 0,
 '881f1a8ee1fffff': 0,
 '881f1a8ebbfffff': 0,
 '881f1a1723fffff': 0,
 '881f1a8e13fffff': 0,
 '881f1a8c2bfffff': 0,
 '881f1a16c9fffff': 0,
 '881f1a16c1fffff': 0,
 '881f1a16d9fffff': 0,
 '881f1a172dfffff': 0,
 '881f1a1503fffff': 0,
 '881f1a1441fffff': 0,
 '881f1a1623fffff': 0,
 '881f1ab933fffff': 0,
 '881f1a98cbfffff': 0,
 '881f1a170dfffff': 0,
 '881f1abb67fffff': 0,
 '881f1ab935fffff': 0,
 '881f1ab957fffff': 0,
 '881f1a1713fffff': 0,
 '881f1ab911fffff': 0,
 '881f1a1461fffff': 0,
 '881f1abb6dfffff': 0,
 '881f1a1703fffff': 0,
 '881f1a8ea1fffff': 0,
 '881f1a1431fffff': 0,
 '881f1a12cbfffff': 0,
 '881f1a8c4dfffff': 0,
 '881f1a12bdfffff': 0,
 '881f1a8ec9fffff': 0,
 '881f1ab9a7fffff': 0,
 '881f1a8c57fffff': 0,
 '881f1a1445fffff': 0,
 '881f1abb07fffff': 0,
 '881f1a1731fffff': 0,
 '881f1a1505fffff': 0,
 '881e3464bbfffff': 0,
 '881f1a8db1fffff': 0,
 '881f1ab94bfffff': 0,
 '881f1a1417fffff': 0,
 '881f1a154bfffff': 0,
 '881f1a15e5fffff': 0,
 '881f1abb0dfffff': 0,
 '881f1a1761fffff': 0,
 '881f1a8c3bfffff': 0,
 '881f1a8dc5fffff': 0,
 '881f1ab805fffff': 0,
 '881f1a1463fffff': 0,
 '881f1ab95bfffff': 0,
 '881f1a1465fffff': 0,
 '881f1a8eb5fffff': 0,
 '881f1a12d1fffff': 0,
 '881f1a8e97fffff': 0,
 '881f1a12d5fffff': 0,
 '881f184909fffff': 0,
 '881f1ab86dfffff': 0,
 '881f1a8c1dfffff': 0,
 '881f1a89d9fffff': 0,
 '881f1a14a9fffff': 0,
 '881f1a8c41fffff': 0,
 '881f1ab917fffff': 0,
 '881f1ab93dfffff': 0,
 '881f1ab82dfffff': 0,
 '881f1a1737fffff': 0,
 '881f1a146bfffff': 0,
 '881f1a8c07fffff': 0,
 '881f1a8c35fffff': 0,
 '881f1aab1bfffff': 0,
 '881f1a8dedfffff': 0,
 '881f18b213fffff': 0,
 '881f1d4d07fffff': 0,
 '881f1d4d61fffff': 0,
 '881f1d4d01fffff': 0}